# Array Creation and Data Typing

[numpy.array](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.array.html) creates an array.

In [2]:
import numpy as np

list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1)

[1 2 3 4]


[numpy.zeros](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.zeros.html) returns a new array of given shape and type, filled with zeros.

In [3]:
array2 = np.zeros(5)
array3 = np.zeros((5,5))
array4 = np.zeros((5,5,5)).astype(int) + 1
array5 = np.zeros(2, dtype=int)
array6 = np.zeros(2, dtype=np.float32)
print('5 zeros:', array2)
print('5x5 matrix:', array3)
print('5x5x5 cube:', array4)
print('int:', array5)
print('float32:', array6)

5 zeros: [ 0.  0.  0.  0.  0.]
5x5 matrix: [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
5x5x5 cube: [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]
int: [0 0]
float32: [ 0.  0.]


[numpy.arange](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.arange.html) returns evenly spaced values within a given interval value.

In [4]:
array7 = np.arange(100)
array8 = np.arange(10, 100)
print('0-100:', array7, '10-100:', array8)

0-100: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99] 10-100: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


[numpy.linspace](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.linspace.html) returns evenly spaced numbers structured by specified interval.

In [5]:
array9 = np.linspace(.0625, 1, 16)
array10 = np.linspace(.03125, 1, 32)
print('16ths of an inch:', array9)
print('32nds of an inch:', array10)

16ths of an inch: [ 0.0625  0.125   0.1875  0.25    0.3125  0.375   0.4375  0.5     0.5625
  0.625   0.6875  0.75    0.8125  0.875   0.9375  1.    ]
32nds of an inch: [ 0.03125  0.0625   0.09375  0.125    0.15625  0.1875   0.21875  0.25
  0.28125  0.3125   0.34375  0.375    0.40625  0.4375   0.46875  0.5
  0.53125  0.5625   0.59375  0.625    0.65625  0.6875   0.71875  0.75
  0.78125  0.8125   0.84375  0.875    0.90625  0.9375   0.96875  1.     ]


[numpy.logspace](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.logspace.html) returns evenly spaced numbers on a log scale.

In [6]:
array11 = np.logspace(0, 1, 100, base=10.0)
print(array11)

[  1.           1.02353102   1.04761575   1.07226722   1.09749877
   1.12332403   1.149757     1.17681195   1.20450354   1.23284674
   1.26185688   1.29154967   1.32194115   1.35304777   1.38488637
   1.41747416   1.45082878   1.48496826   1.51991108   1.55567614
   1.59228279   1.62975083   1.66810054   1.70735265   1.7475284
   1.78864953   1.83073828   1.87381742   1.91791026   1.96304065
   2.009233     2.05651231   2.10490414   2.15443469   2.20513074
   2.25701972   2.3101297    2.36448941   2.42012826   2.47707636
   2.53536449   2.59502421   2.65608778   2.71858824   2.7825594
   2.84803587   2.91505306   2.98364724   3.05385551   3.12571585
   3.19926714   3.27454916   3.35160265   3.43046929   3.51119173
   3.59381366   3.67837977   3.76493581   3.85352859   3.94420606
   4.03701726   4.1320124    4.22924287   4.32876128   4.43062146
   4.53487851   4.64158883   4.75081016   4.86260158   4.97702356
   5.09413801   5.21400829   5.33669923   5.46227722   5.59081018
   5.7223676

[numpy.ones](https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.ones.html) returns a new array of given shape and type, filled with ones.

In [7]:
cube1 = np.ones((5, 5, 5)).astype(np.float16)
print(cube1)

[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]]


## Reshaping
 - create 1D array
 - reshape 1D array to 3D array

In [11]:
arr1d = np.arange(1000)
arr3d = arr1d.reshape((10, 10, 10))
arr3d = np.reshape(arr1d, (10, 10, 10)) # alt
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()
print(arr1d.shape)
print(arr4d)

(10000,)
[[[[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  ..., 
  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]]

  [[ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   [ 0.  0.  0. ...,  0.  0.  0.]
   ..., 
   [ 0.  0. 