# Indexing and Slicing

`alist[0][1]` indexes 2nd element of 1st list which returns `2`.

In [1]:
import numpy as np

alist = [[1,2],[3,4]]
print(alist[0][1])

2


But to index an entire row or an entire list, the list above must can be converted to a numpy array.
 - `arr1[0,1]` indexes 2nd element in 1st list, which returns `2`.
 - `arr1[:,1]` indexes 2nd elements of both lists, which returns `[2 4]`
 - `arr1[1,:]` indexes both elements in 2nd list, which returns `[3 4]`

In [1]:
arr1 = np.array(alist)  # [[1 2] [3 4]]
print(arr1)
print(arr1[0,1])
print(arr1[:,1])
print(arr1[1,:])

[[1 2]
 [3 4]]
2
[2 4]
[3 4]


## Conditional Indexing

In [1]:
arr2 = np.arange(5)
index = np.where(arr2 > 2)
print(index)
new_arr1 = np.delete(arr, index)
print(new_arr1)

(array([3, 4]),)
[0 1 2]


### Alternative

Use conventional conditional indexing (which may require less code).

In [1]:
arr3 = np.arange(5)
index = arr3 > 2
new_arr2 = arr3[index]
print(new_arr2)

[3 4]
